name: Data Preprocessing Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-process:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pandas numpy scikit-learn

      - name: Run Preprocessing Script
        run: python preprocessing/automate_Muhammad-Faturrohman.py

      - name: Commit and Push processed data
        env: 
          MY_USERNAME: ${{ secrets.USERNAME }}
          MY_EMAIL: ${{ secrets.EMAIL }}
        run: |
          # Menggunakan environment variable yang sudah di-load
          git config --global user.name "$MY_USERNAME"
          git config --global user.email "$MY_EMAIL"
          
          # Add file hasil
          git add mushrooms_preprocessing/mushrooms_clean.csv
          
          # Commit & Push
          git commit -m "Auto-update: Dataset processed by $MY_USERNAME via GitHub Actions" || echo "No changes to commit"
          git push