name: Preprocessing Dataset

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn

      - name: Run preprocessing
        run: |
          cd preprocessing
          python automate_Muhammad Faturrohman.py

      - name: Commit processed dataset
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add .
          git commit -m "Update preprocessing dataset" || echo "No changes"
          git push